# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack: templates'
  inputs:
    command: 'pack'
    packagesToPack: 'src/Tradmia.Tmplates.csproj'
    arguments: '--configuration $(buildConfiguration)'    

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: NuGetCommand@2
  displayName: 'dotnet push: templates'
  inputs:
    command: push
    publishVstsFeed: '8da0b56e-ff46-40c2-b1ce-0e49f5c5dd96'
    allowPackageConflicts: true